### ISSUE TITLE
Fautes d'anglais.

### ISSUE THREAD

**Issue by LeoBdt** [HighLev-PM/HoodHelmet#1]
Dans le config.yml

"Well done, you've an invisible nickname"

**Comment by Seyz123** [comment]
Mais t'es partout toi

**Comment by Seyz123** [comment]
Voilà, voilà..

**Comment by LeoBdt** [comment]
Léo codeur de l'ombre baiseur de la lueur

**Comment by Palente** [comment]
Issue non intéressante.

**Comment by LeoBdt** [comment]
Palente rage pas si tu sais pas écrire en anglais non plus

**Comment by Palente** [comment]
Mais l'issue est fermé tu n'a pas la permission de re commenter

**Comment by Seyz123** [comment]
Hey! C'est fermé.. Go Discord si vous voulez vous battre..

**Comment by LeoBdt** [comment]
ah, désolé mec
